In [1]:
# Import python libraries required in this example:
from keras.models import Sequential
from keras.layers import Dense, Activation
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
dataset = pd.read_excel("Dataset_NN_NB.xlsx",header = 0)
dataset.head()

Age  Gender  Experience  Tenure in Company  Performance Score  \
0   45       2          21                 17                  2   
1   49       2          26                 18                  2   
2   52       2          29                 28                  3   
3   49       2          26                 22                  1   
4   45       2          21                 17                  5   

   Customer Rating  Nature of Job  attrition  
0                2              1          1  
1                5              2          1  
2                4              2          1  
3                4              1          1  
4                5              1          1

In [63]:
# creation of Skeleton model
model = Sequential()
model.add(Dense(50, input_shape=(7,))) # Defining the Hidden layers and neurons
model.add(Activation('sigmoid'))      # Activation function in the Hidden Layer
model.add(Dense(1))                   # Output Layer definition
model.add(Activation('sigmoid'))      # Activation function in Output Layer
# Compile the model and calculate its accuracy:
model.compile(loss='mse', optimizer='sgd', metrics=['accuracy']) # sgd - stochastic gradient Descent
# Print a summary of the Keras model:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_10 (Dense)            (None, 50)                400       
                                                                 
 activation_10 (Activation)  (None, 50)                0         
                                                                 
 dense_11 (Dense)            (None, 1)                 51        
                                                                 
 activation_11 (Activation)  (None, 1)                 0         
                                                                 
Total params: 451
Trainable params: 451
Non-trainable params: 0
_________________________________________________________________


In [64]:
x = np.array(dataset[['Age','Gender','Experience', 'Tenure in Company','Performance Score','Customer Rating','Nature of Job']])
y = np.array(dataset.attrition);


In [65]:
x_train, x_test, y_train, y_test= train_test_split(x, y, train_size=0.8)

In [66]:
print(len(x_train))
print(len(y_train))
print(len(x_test))
print(len(y_test))
y_test

240
240
60
60


array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0], dtype=int64)

In [67]:
mdl = model.fit(x_train,y_train, epochs=20, batch_size = 80)

Epoch 1/20
3/3 [==============================] - 1s 9ms/step - loss: 0.3398 - accuracy: 0.5042
Epoch 2/20
3/3 [==============================] - 0s 8ms/step - loss: 0.3264 - accuracy: 0.5042
Epoch 3/20
3/3 [==============================] - 0s 7ms/step - loss: 0.3108 - accuracy: 0.5042
Epoch 4/20
3/3 [==============================] - 0s 4ms/step - loss: 0.2921 - accuracy: 0.5042
Epoch 5/20
3/3 [==============================] - 0s 8ms/step - loss: 0.2721 - accuracy: 0.5042
Epoch 6/20
3/3 [==============================] - 0s 9ms/step - loss: 0.2548 - accuracy: 0.5042
Epoch 7/20
3/3 [==============================] - 0s 3ms/step - loss: 0.2409 - accuracy: 0.5042
Epoch 8/20
3/3 [==============================] - 0s 4ms/step - loss: 0.2315 - accuracy: 0.5208
Epoch 9/20
3/3 [==============================] - 0s 4ms/step - loss: 0.2253 - accuracy: 0.6333
Epoch 10/20
3/3 [==============================] - 0s 2ms/step - loss: 0.2207 - accuracy: 0.7375
Epoch 11/20
3/3 [======================

In [68]:
y_pred = model.predict(x_test)

2/2 [==============================] - 0s 0s/step


In [69]:
y_pred

array([[0.43797272],
       [0.49242046],
       [0.4191553 ],
       [0.5133179 ],
       [0.5898435 ],
       [0.4361959 ],
       [0.4057673 ],
       [0.5124915 ],
       [0.49180594],
       [0.41277438],
       [0.5322298 ],
       [0.36884356],
       [0.5965875 ],
       [0.43884683],
       [0.5608709 ],
       [0.43421715],
       [0.41441342],
       [0.59050506],
       [0.5860818 ],
       [0.49988464],
       [0.5875649 ],
       [0.41843542],
       [0.39012995],
       [0.47630328],
       [0.58814037],
       [0.5191566 ],
       [0.5954127 ],
       [0.42074782],
       [0.4129291 ],
       [0.5750197 ],
       [0.44148156],
       [0.43030116],
       [0.5791642 ],
       [0.5497621 ],
       [0.537094  ],
       [0.50492436],
       [0.51385456],
       [0.4808567 ],
       [0.5996456 ],
       [0.50971526],
       [0.59959805],
       [0.5213246 ],
       [0.4829702 ],
       [0.41929075],
       [0.46518663],
       [0.5146186 ],
       [0.56445634],
       [0.482

In [70]:
y_pclass = np.where(y_pred>=0.5,1,0)

In [71]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
cm = confusion_matrix(y_test, y_pclass)
print (cm)
print(f1_score(y_test, y_pclass))

[[24  2]
 [ 4 30]]
0.9090909090909091


In [72]:
print(accuracy_score(y_test, y_pclass))

0.9
